### ISSUE TITLE
bug related to nokogiri

### ISSUE THREAD

**Issue by baudoliver7** [g4s8/pdd-action#1]
While building dockerfile, we noticed that there is an http error `403` related to the downloading of file : https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.0-x64-unknown.gemspec.rz (see [here](https://github.com/cqfn/eo/runs/4769191737?check_suite_focus=true))

**Comment by baudoliver7** [comment]
@g4s8 WDYT ?

**Comment by baudoliver7** [comment]
@g4s8 still have some issues (now about nokogiri files location).
see [here](https://github.com/artipie/artipie/runs/4893238388?check_suite_focus=true).

**Comment by g4s8** [comment]
@baudoliver7 yes, I see. Now the build is fine but `pdd` fails to run with some errors, I reported a bug about it: https://github.com/cqfn/pdd/issues/191

**Comment by baudoliver7** [comment]
@g4s8 good :)
